### ISSUE TITLE
/campaign/helloworld rewrite doesn't work

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-helloworld-publish-dispatcher#5]
/campaign/helloworld path should show the same content as /content/helloworld.html .
It currently shows a 404 page.

**Comment by ibi456** [comment]
issue fixed with [https://github.com/shinesolutions/aem-helloworld-publish-dispatcher/pull/6](url)

**Comment by cliffano** [comment]
Done. Included in v0.9.1 .
